#!/bin/bash
# 3个月数据回测脚本

DATA_SOURCE=binance \
MARKET_SYMBOL=BTC/USDT \
MARKET_TIMEFRAME=1h \
BACKTEST_MONTHS=3 \
FUTURES_USE_ENHANCED_STRATEGY=True \
FUTURES_LEVERAGE=3 \
FUTURES_RISK_PER_TRADE=0.02 \
MARKET_TYPE=future \
python3 main.py
